apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webapp
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-webapp'
    spec:
      project: default
      source:
        repoURL: https://github.com/abozzoni/kustomize-bs.git
        targetRevision: HEAD
        path: webapp/overlays/development
      destination:
        server: '{{url}}'
        #namespace: webapp-{{cluster}}
